language: d

matrix:
  include:
    - d: dmd-2.087.1
      script:
        - dub test -b unittest-cov
        - dub build -b ddox
      env:
        # travis encrypt -r thaven/oauth GH_TOKEN=123456789abcdef
        secure: "gQsokyoWNjc7WBRvNs/fkNoJwJoPid7o2V0pTXZj4NW1kZ0wb7xvjjt41t4dI3UaXD7qMsKp/fVGwN76qFof0H+u0RwLHOjff45srrxNJDRSiWWvdc7qrt4Jc4q/Fli6FqL+FHoYk9ByGQVtseU225EiiYQE9KfYH46aSmeSEUIHNfh/+QS3Dh9Ua3mq7q8o1G06fyWNOt33WwwX/GmmFlqTS7IzKgEej0O+38X5dkUcnRdyRopipT83FsBMLfxL8HxvAz86LPag5bVl9lQBxhY4EKjicv0nosrDT18LXd+z4uQNhEU23OOBtP5H5JI6+WuJXX+ZjiqEqdwiSn5UgyRKw5O/gmAWwZFGmn21thd1j8FMvIwdNqTh9/AeH5CgK1NpB3vN89nKW9enP17kwLo81Ijoad1+0Yh39jAlKMK1UWgQB6tnIoXfnzGDYTbTZ/Z171GJJ+6BCdF6YnbA9YdZw9SzIV8S0e1wkztnzqlfIMkainXXMyzhN6x+Ys9znzjQ1mUwlrjQ+D0mFBtfVjpdELE3sMiHaYIYSMHH0T6EK9dypo0b2IpQPhGQM4tPh4jbV8pY9q07lMRFa7kTIX7JW0VpQ0E219J7gHYChza/ko9dPAImkrZVkS2Vm4vPF1EWKLEC5lpmP7BvDfm8mxP1N73KdxR3uvye4YbrNsM="
      addons: { apt: { packages: [libevent-dev] } }
      after_success: bash <(curl -s https://codecov.io/bash)

      deploy:
        local_dir: docs
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        on:
          branch: master
