language: d

matrix:
  include:
    - d: dmd-2.094.0
      script:
        - dub test -b unittest-cov
        - dub build -b ddox
      addons: { apt: { packages: [libevent-dev] } }
      after_success: bash <(curl -s https://codecov.io/bash)

      deploy:
        local_dir: docs
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        on:
          branch: master
